### ISSUE TITLE
Can you optimize this function?

### ISSUE THREAD

**Issue by maogouriji** [lrzjason/Comfyui-In-Context-Lora-Utils#1]
This feature is really very convenient, but I encountered some problems when using it, for example, after inputting two images, if the height of the two images is different, after the node will lead to image cropping

**Comment by lrzjason** [comment]
I have updated the workflow and added new node for context editing which could solve this issue. 
workflow: https://civitai.com/models/933018?modelVersionId=1110698 
parameter: https://civitai.com/articles/9292
