### ISSUE TITLE
Can we add a black background mask

### ISSUE THREAD

**Issue by yincangshiwei** [lrzjason/Comfyui-In-Context-Lora-Utils#2]
I want a mask background that highlights the redrawn items on the left side：
![image](https://github.com/user-attachments/assets/c6dfea41-2246-42de-9847-ffc01ec20657)

![image](https://github.com/user-attachments/assets/b672da50-8d2c-4200-8003-0bf6bf188fba)
![image](https://github.com/user-attachments/assets/8ac88364-0ab4-4853-afeb-bbffc680b66e)

**Comment by lrzjason** [comment]
You might use new workflow with new node. 

With new node: AutoPatch, CreateContextWindow and ConcatContextWindow
You could mask any area on reference image and any area on target image

https://civitai.com/models/933018/flux-context-window-editing-v31-fill-model-fix-anything-in-any-context

**Comment by lrzjason** [comment]
Something like this:
![B7 (%S`B_P`J0%TSFBP S2](https://github.com/user-attachments/assets/3b535ac9-ebb4-45c8-a5ed-2e26aa85bd1e)

**Comment by yincangshiwei** [comment]
> You might use new workflow with new node.
> 
> With new node: AutoPatch, CreateContextWindow and ConcatContextWindow You could mask any area on reference image and any area on target image
> 
> https://civitai.com/models/933018/flux-context-window-editing-v31-fill-model-fix-anything-in-any-context

I added 'patch_left' to solve the problem, and then added # 000000 to the color chart, which will improve the effect of fill+redus repainting.
![image](https://github.com/user-attachments/assets/d7964e5b-3e9a-49f3-8b57-3791016b4534)
